# -*- coding: utf-8 -*-
"""manhole_detection.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17y_jVvdJedZ2PR7GdVjLFkaDkW42XIUB
"""

from google.colab import drive
drive.mount('/content/drive')

!pip install ultralytics

import cv2
import matplotlib.pyplot as plt
import numpy as np
import os
from ultralytics import YOLO

# ---------------------------------------------------------------------------
# 1. Get the dataset
# ---------------------------------------------------------------------------
# The variable `dataset_path` was incorrectly set to the data.yaml file itself.
# It should point to the root directory of the dataset.
# For clarity, let's define the path to the data.yaml file and then the dataset's root directory.
data_yaml_file_path = "/content/drive/MyDrive/archive (5)/data.yaml"
dataset_root_for_tree = os.path.dirname(data_yaml_file_path)

print(f"data.yaml file path: {data_yaml_file_path}")
print(f"Dataset root for directory listing: {dataset_root_for_tree}")

# Use the actual dataset root for os.walk
if os.path.isdir(dataset_root_for_tree):
    for root, dirs, files in os.walk(dataset_root_for_tree):
        level = root.replace(dataset_root_for_tree, '').count(os.sep)
        indent = ' ' * 4 * level
        print(f'{indent}{os.path.basename(root)}/')
        for f in files[:5]:  # cap printout, some of these dirs are large
            print(f'{indent}    {f}')
else:
    print(f"Warning: The path '{dataset_root_for_tree}' is not a directory. Skipping directory listing.")


# IMPORTANT: open the printed tree (or the file below) and confirm the class
# names before training -- don't assume they match another dataset.
# Use the correctly identified data_yaml_file_path for reading the YAML.
data_yaml_path = data_yaml_file_path # Assigning to data_yaml_path for consistency with other cells
print("\ndata.yaml contents:")
with open(data_yaml_path) as f:
    print(f.read())

from ultralytics import YOLO
import shutil
import os

model = YOLO("yolov8s.pt")  # small, not nano -- better accuracy for similar speed

model.train(
    data=data_yaml_path,
    epochs=100,
    patience=20,           # early stopping once val metrics plateau
    imgsz=832,             # manholes are small in frame; 640 loses detail
    batch=16,
    project="OpenManhole",
    name="YOLOv8",

    # augmentation aimed at occlusion + the rare open/missing class
    hsv_h=0.015, hsv_s=0.6, hsv_v=0.5,
    degrees=8.0, perspective=0.0003,
    translate=0.1, scale=0.4,
    fliplr=0.5, mosaic=1.0,
    erasing=0.3,
    copy_paste=0.2,
    cos_lr=True,
)

# Copy the complete training folder to Google Drive
source = "/content/runs/detect/OpenManhole/YOLOv8"
destination = "/content/drive/MyDrive/OpenManhole_Project"

shutil.copytree(source, destination, dirs_exist_ok=True)

print("✅ Training results saved to Google Drive!")

# Load best model from Google Drive
best_weights = "/content/drive/MyDrive/OpenManhole_Project/weights/best.pt"
model = YOLO(best_weights)

# ---------------------------------------------------------------------------
# 3. Evaluate -- per-class recall, not just the mean
# ---------------------------------------------------------------------------
metrics = model.val(data=data_yaml_path, split="test")
names = model.names

print("\n=== Overall ===")
print("mAP50   :", metrics.box.map50)
print("mAP50-95:", metrics.box.map)

print("\n=== Per-class precision / recall (default conf=0.25) ===")
for i, name in names.items():
    try:
        print(f"  {name:15s}  P={metrics.box.p[i]:.3f}  R={metrics.box.r[i]:.3f}")
    except (IndexError, AttributeError):
        pass

# Identify which class index is the "open"/"missing"/"uncovered" one --
# EDIT this to match whatever the dataset's data.yaml actually calls it.
rare_class_keywords = ("open", "missing", "uncovered")
rare_idx = next((i for i, n in names.items() if any(k in n.lower() for k in rare_class_keywords)), None)

if rare_idx is not None:
    print(f"\n=== Confidence sweep on '{names[rare_idx]}' (target: recall >= 0.90) ===")
    print(f"{'conf':>6} {'precision':>10} {'recall':>10}")
    for conf in np.arange(0.05, 0.65, 0.05):
        m = model.val(data=data_yaml_path, split="test", conf=float(conf), verbose=False)
        try:
            p, r = m.box.p[rare_idx], m.box.r[rare_idx]
            print(f"{conf:6.2f} {p:10.3f} {r:10.3f}")
        except (IndexError, AttributeError):
            continue
    print(
        "\nPick the lowest confidence threshold that still gives acceptable "
        "precision -- that's your deployment threshold. Route the resulting "
        "false positives to human review rather than raising the threshold "
        "to suppress them."
    )
else:
    print("\nCouldn't auto-detect the open/missing class name -- check names:", names)

# ---------------------------------------------------------------------------
# 4. Visual check on test images
# ---------------------------------------------------------------------------
test_images_dir = os.path.join(dataset_root_for_tree, "test", "images")

results = model.predict(
    source=test_images_dir,
    save=True,
    conf=0.15,  # recall-favoring, not 0.4 -- see the sweep above for tuning
)

print(f"Displaying predictions for {min(5, len(results))} images...")
for i, result in enumerate(results[:5]):
    im_bgr = result.plot()
    im_rgb = cv2.cvtColor(im_bgr, cv2.COLOR_BGR2RGB)
    plt.figure(figsize=(12, 10))
    plt.imshow(im_rgb)
    plt.title(f"Prediction for image {i+1}")
    plt.axis('off')
    plt.show()

metrics = model.val(data=data_yaml_path, split="test")

print("mAP50:", metrics.box.map50)
print("mAP50-95:", metrics.box.map)

model.predict(
    source="/content/drive/MyDrive/manhole image",
    conf=0.5,
    save=True
)

from ultralytics import YOLO

# Load the best model from the path where it was saved in Google Drive
model = YOLO(best_weights)

metrics = model.val(
    data=data_yaml_path # Use the dynamically determined data.yaml path
)

print(metrics)

metrics.confusion_matrix

from ultralytics import YOLO

# Load the best model from the path where it was saved in Google Drive
model = YOLO(best_weights)

metrics = model.val(
    data=data_yaml_path # Use the dynamically determined data.yaml path
)

print(metrics)

from google.colab import files
from ultralytics import YOLO
from IPython.display import display, Image
import os

# Load model
model = YOLO("/content/drive/MyDrive/OpenManhole_Project/weights/best.pt")

# Upload image
uploaded = files.upload()

# Get uploaded image path
image_path = next(iter(uploaded))

# Predict
results = model.predict(
    source=image_path,
    conf=0.7,
    save=True
)

# Get saved result folder
save_dir = results[0].save_dir

# Path of detected image
result_image = os.path.join(save_dir, image_path)

print("Results saved to:", save_dir)

# Display original image
print("\nOriginal Image:")
display(Image(filename=image_path))

# Display YOLO detection result
print("\nYOLO Detection Result:")

if os.path.exists(result_image):
    display(Image(filename=result_image))
else:
    # Sometimes YOLO changes filename, so search inside folder
    files_in_folder = os.listdir(save_dir)
    print("Searching detected image...")

    if len(files_in_folder) > 0:
        result_image = os.path.join(save_dir, files_in_folder[0])
        display(Image(filename=result_image))
    else:
        print("Detection image not found")

from ultralytics import YOLO
from google.colab import files
from IPython.display import Video, display
import os
import subprocess

# ==========================================
# 1. Load trained model
# ==========================================
model = YOLO("/content/drive/MyDrive/OpenManhole_Project/weights/best.pt")

# ==========================================
# 2. Upload video
# ==========================================
print("Upload your video:")
uploaded = files.upload()

video_path = next(iter(uploaded))

print("Uploaded:", video_path)

# ==========================================
# 3. Run YOLO detection
# ==========================================
results = model.predict(
    source=video_path,
    conf=0.7,
    save=True
)

save_dir = str(results[0].save_dir)

print("Detection completed!")
print("YOLO output folder:", save_dir)

# ==========================================
# 4. Find YOLO output video
# ==========================================
output_video = None

for file in os.listdir(save_dir):
    if file.lower().endswith((".mp4", ".avi", ".mov", ".mkv")):
        output_video = os.path.join(save_dir, file)
        break

if output_video is None:
    print("❌ YOLO output video not found")
else:
    print("YOLO output:", output_video)

    # ==========================================
    # 5. Convert to browser-compatible MP4
    # ==========================================
    playable_video = "/content/manhole_detection_playable.mp4"

    command = [
        "ffmpeg",
        "-y",
        "-i", output_video,
        "-vcodec", "libx264",
        "-acodec", "aac",
        "-pix_fmt", "yuv420p",
        playable_video
    ]

    subprocess.run(command, stdout=subprocess.PIPE, stderr=subprocess.PIPE)

    # ==========================================
    # 6. Check converted video
    # ==========================================
    if os.path.exists(playable_video):

        print("\n✅ Video ready!")
        print("YOLO Detection Result:")

        display(Video(
            playable_video,
            embed=True,
            width=800
        ))

    else:
        print("❌ Video conversion failed")